### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by yemen2016** [sloria/TextBlob#213] opened 2018-06-13 14:44 UTC
I have trained my model using textblob with almost 2000 of news headlines. I got this error:
MemoryError
Please help to solve this problem.

**Comment by sloria** [comment] 2018-12-16 01:18
This is a duplicate of #176 .

**Closed by sloria** 2018-12-16 01:18 UTC

**Comment by cmazzoni87** [comment] 2019-01-11 03:50
The thread #176 was closed but not answered.

**Comment by arnabchoudhury1** [comment] 2019-03-26 07:11
Anybody knows a fix for this..??
