### ISSUE TITLE
Error in translation and detect_language

### ISSUE THREAD

**Issue by DennisvDijk** [sloria/TextBlob#396] opened 2021-09-14 09:56 UTC
Hi,

When calling for the functions detect_language & translate are not working. After a couple of pushes, I receive a HTTP 404 error unfortunately. I'm quite unsure what the issue might be. I don't if Google updated their criteria regarding API's but @sloria could you have a look at this? I'm happy to help.

**Comment by yes-G** [comment] 2021-09-14 11:11
Possibly duplicate of  #395

**Comment by sloria** [comment] 2021-09-14 12:59
Let's continue discussion in #395

**Closed as completed** 2021-09-14 12:59 UTC
